/*
 * app.c - UART ping-pong logic for STM32CubeIDE projects.
 * Needs: USART1 (115200 8N1) with DMA RX circular (Ch5) + DMA TX normal (Ch4),
 *        USART1 global interrupt enabled, PC13 as GPIO output (LED).
 * Also copy protocol.h / protocol.c into Core/Inc and Core/Src.
 */
#include "main.h"
#include "app.h"
#include "protocol.h"

#define RX_BUF_SIZE        128u
#define PARSER_TIMEOUT_MS  100u

extern UART_HandleTypeDef huart1;            /* generated by CubeMX */

static uint8_t           rx_buf[RX_BUF_SIZE];
static volatile uint16_t rx_head;            /* written by ISR (DMA position) */
static uint16_t          rx_tail;            /* read by main loop             */

static uint8_t           tx_buf[PROTO_MAX_PACKET];
static volatile uint8_t  tx_busy;
static volatile uint8_t  uart_error;

static proto_parser_t    parser;
static uint32_t          last_rx_tick;

static void handle_packet(const proto_packet_t *pkt)
{
    size_t n;

    switch (pkt->cmd) {
    case PROTO_CMD_PING:
        HAL_GPIO_TogglePin(GPIOC, GPIO_PIN_13);              /* LED feedback */
        n = proto_encode(tx_buf, PROTO_CMD_PONG, pkt->payload, pkt->len);
        break;

    case PROTO_CMD_PONG:                     /* never answer PONG/ERROR:      */
    case PROTO_CMD_ERROR:                    /* avoids endless ping-pong      */
        return;

    default: {
        uint8_t code = PROTO_ERRCODE_UNKNOWN_CMD;
        n = proto_encode(tx_buf, PROTO_CMD_ERROR, &code, 1);
        break;
    }
    }

    tx_busy = 1;                             /* set BEFORE starting DMA */
    if (HAL_UART_Transmit_DMA(&huart1, tx_buf, (uint16_t)n) != HAL_OK) tx_busy = 0;
}

void app_init(void)
{
#ifdef DEBUG
    HAL_DBGMCU_EnableDBGSleepMode();         /* keep debugger alive during WFI */
#endif
    HAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, GPIO_PIN_SET);     /* LED off (active low) */
    proto_parser_init(&parser);
    if (HAL_UARTEx_ReceiveToIdle_DMA(&huart1, rx_buf, RX_BUF_SIZE) != HAL_OK)
        Error_Handler();
}

void app_loop(void)
{
    if (uart_error) {                        /* overrun / framing / DMA error */
        uart_error = 0;
        HAL_UART_Abort(&huart1);
        tx_busy = 0;
        rx_head = rx_tail = 0;
        proto_parser_init(&parser);
        HAL_UARTEx_ReceiveToIdle_DMA(&huart1, rx_buf, RX_BUF_SIZE);
    }

    /* Drain DMA buffer; pause while a response is still being sent (only one
     * TX frame in flight -> a single tx_buf is enough). */
    while (rx_tail != rx_head && !tx_busy) {
        uint8_t b = rx_buf[rx_tail];
        rx_tail = (uint16_t)((rx_tail + 1u) % RX_BUF_SIZE);
        last_rx_tick = HAL_GetTick();

        if (proto_parser_feed(&parser, b) == PROTO_PACKET_OK)
            handle_packet(&parser.packet);
    }

    /* Half-received packet and silent line -> resynchronise */
    if (parser.state != PROTO_S_HEAD &&
        (HAL_GetTick() - last_rx_tick) > PARSER_TIMEOUT_MS)
        proto_parser_init(&parser);

    /* Sleep until next interrupt (PRIMASK trick: no lost wake-up) */
    __disable_irq();
    if ((rx_tail == rx_head || tx_busy) && !uart_error) __WFI();
    __enable_irq();
}

/* ---- HAL callbacks (interrupt context, kept tiny) ---- */
void HAL_UARTEx_RxEventCallback(UART_HandleTypeDef *huart, uint16_t Size)
{
    if (huart->Instance == USART1)
        rx_head = (uint16_t)(Size % RX_BUF_SIZE);
}

void HAL_UART_TxCpltCallback(UART_HandleTypeDef *huart)
{
    if (huart->Instance == USART1) tx_busy = 0;
}

void HAL_UART_ErrorCallback(UART_HandleTypeDef *huart)
{
    if (huart->Instance == USART1) uart_error = 1;
}
